---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Cytoconnect 2025 Spatial Workshop.

# Analysis Overview {-}

For the visium analysis, we will be using the colorectal cancer data from 10x.
The data can be found [here](https://www.10xgenomics.com/platforms/visium/product-family/dataset-human-crc).

Publication for the data:
```
Oliveira, M.F.d., Romero, J.P., Chung, M. et al. 
High-definition spatial transcriptomic profiling of immune cell populations in colorectal cancer. 
Nat Genet 57, 1512–1523 (2025). 
https://doi.org/10.1038/s41588-025-02193-3
```

## Setup

| Rmd file                                        | Topics                        |
|:---------                                       |:-----------------------------|
| [setup](setup.html)                             | Downloading data and packages|

Please run codes in the Rmd file before coming to the workshop.

## Spatial Transcriptomics (Visium)

| Rmd file                                        | Topics                          |
|:---------                                       |:--------------------------------|
| [visium_01](visium_01.html)                     | Introduction to data            |   
|                                                 | Loading data into Seurat object |
|                                                 | Interacting with Seurat object  |
|                                                 |                                 |
| [visium_02](visium_02.html)                     | QC and Normalisation            | 
|                                                 |                                 |
| [visium_03](visium_03.html)                     | Visualising spatial data        |
|                                                 |                                 |
| [visium_04](visium_04.html)                     | Module scoring                  |
|                                                 | Deconvolution                   |
|                                                 | Find Spatially Variable genes   |
|                                                 | Other spatial based analyses    |
|                                                 |                                 |

## Imaging Mass Cytometry (IMC)
| Rmd file                                        | Topics                                  |
|:---------                                       |:---------------------------------------|
| [imc_01](imc_01.html)                           | Segmentation using ImageJ and Mesmer   |   
|                                                 | Loading and visualising data in Qupath |
| [imc_02](imc_02.html)                           | Basic downstream analysis using R      |